//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Welenda.lk
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.productdetails = new HashSet<productdetail>();
            this.productinfoes = new HashSet<productinfo>();
            this.usertobaskets = new HashSet<usertobasket>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string imgurl { get; set; }
        public string oldprice { get; set; }
        public string newprice { get; set; }
        public Nullable<bool> ishotproduct { get; set; }
        public Nullable<int> mainCategory { get; set; }
        public Nullable<int> mainSubCategory { get; set; }
        public Nullable<int> subCategory { get; set; }
        public Nullable<bool> isinhomepage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productdetail> productdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productinfo> productinfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usertobasket> usertobaskets { get; set; }
    }
}
