//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Welenda.lk
{
    using System;
    using System.Collections.Generic;
    
    public partial class productdetail
    {
        public int id { get; set; }
        public string mainimageurl { get; set; }
        public string subimageurl { get; set; }
        public string details { get; set; }
        public int productid { get; set; }
    
        public virtual product product { get; set; }
    }
}
